/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const errorResponseSchema = z.object({
  code: z.number().int().optional(),
  error: z
    .object({
      message: z.string().optional(),
      section: z.string().optional(),
    })
    .optional(),
  message: z.string().optional(),
  status: z.string().optional(),
  type: z.number().int().optional(),
});
