/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { z } from "zod";

export const getChatsSchema = z.object({
  chats: z
    .array(
      z.object({
        created_at: z.string().datetime().optional(),
        id: z.number().int().min(0).optional(),
        last_message_time: z.string().datetime().optional(),
        seen: z.boolean().optional(),
        updated_at: z.string().datetime().optional(),
        user1_id: z.number().int().min(0).optional(),
        user2_id: z.number().int().min(0).optional(),
      }),
    )
    .optional(),
  users: z
    .array(
      z.object({
        created_at: z.string().datetime().optional(),
        email: z.string().optional(),
        first_name: z.string().optional(),
        id: z.number().int().optional(),
        surname: z.string().optional(),
        username: z.string().optional(),
      }),
    )
    .optional(),
});

/**
 * @description Chats retrieved
 */
export const getChats200Schema = z.lazy(() => getChatsSchema);

/**
 * @description Failure
 */
export const getChats400Schema = z.lazy(() => errorResponseSchema);

export const getChatsErrorSchema = z.any();

export const getChatsQueryResponseSchema = z.lazy(() => getChats200Schema);
