/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { z } from "zod";

export const getEvaluationKeySchema = z.object({
  file: z.string().optional(),
  id: z.string().optional(),
  user_id: z.number().int().optional(),
});

/**
 * @description Get eval key success
 */
export const getEvaluationKey200Schema = z.lazy(() => getEvaluationKeySchema);

/**
 * @description Failure
 */
export const getEvaluationKey400Schema = z.lazy(() => errorResponseSchema);

export const getEvaluationKeyErrorSchema = z.any();

export const getEvaluationKeyQueryResponseSchema = z.lazy(
  () => getEvaluationKey200Schema,
);
