/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { z } from "zod";

export const getMessagesCountPathParamsSchema = z.object({
  chatID: z.coerce.number().int(),
});

export const getMessagesCountQueryParamsSchema = z
  .object({
    skip: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
  })
  .optional();

/**
 * @description Count retrieved
 */
export const getMessagesCount200Schema = z.number().int();

/**
 * @description Failure
 */
export const getMessagesCount400Schema = z.lazy(() => errorResponseSchema);

export const getMessagesCountErrorSchema = z.any();

export const getMessagesCountQueryResponseSchema = z.lazy(
  () => getMessagesCount200Schema,
);
