/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { getRefreshAuthResponseSchema } from "./getRefreshAuthResponseSchema";
import { z } from "zod";

/**
 * @description Refresh Authentication success
 */
export const getRefreshToken200Schema = z.lazy(
  () => getRefreshAuthResponseSchema,
);

/**
 * @description Failure
 */
export const getRefreshToken400Schema = z.lazy(() => errorResponseSchema);

export const getRefreshTokenErrorSchema = z.any();

export const getRefreshTokenQueryResponseSchema = z.lazy(
  () => getRefreshToken200Schema,
);
