/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { z } from "zod";

export const getUserSchema = z.object({
  email: z.string().optional(),
  first_name: z.string().optional(),
  id: z.number().int().optional(),
  surname: z.string().optional(),
  username: z.string().optional(),
});

/**
 * @description User retrieved
 */
export const getUser200Schema = z.lazy(() => getUserSchema);

/**
 * @description Failure
 */
export const getUser400Schema = z.lazy(() => errorResponseSchema);

export const getUserErrorSchema = z.any();

export const getUserQueryResponseSchema = z.lazy(() => getUser200Schema);
