/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const inferenceEventSchema = z.object({
  chat_id: z.number().int().min(0).optional(),
  classification_result: z.string().optional(),
  content: z.string().optional(),
  finished: z.boolean().optional(),
  id: z.number().int().min(0).nullable().nullish(),
  image: z.string().optional(),
  image_to_classify: z.string().optional(),
  is_typing: z.boolean().optional(),
  iv: z.string().optional(),
  receiver_id: z.number().int().min(0).optional(),
  sender_id: z.number().int().min(0).optional(),
  sender_name: z.string().optional(),
  timestamp: z.string().datetime().optional(),
  type: z.string().optional(),
});
