/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const postEvaluationKeyBodySchema = z.object({
  chat_id: z.number().int().min(0).optional(),
  file: z.string().optional(),
});
