/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const postAuthResponseSchema = z.object({
  access_token: z.string().optional(),
  exp: z.string().datetime().optional(),
  refresh_token: z.string().optional(),
  user: z
    .object({
      created_at: z.string().datetime().optional(),
      email: z.string().optional(),
      first_name: z.string().optional(),
      id: z.number().int().optional(),
      surname: z.string().optional(),
      username: z.string().optional(),
    })
    .optional(),
});
