/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const postChatsResponseSchema = z.object({
  created_at: z.string().datetime().optional(),
  id: z.number().int().min(0).optional(),
  last_message_time: z.string().datetime().optional(),
  seen: z.boolean().optional(),
  updated_at: z.string().datetime().optional(),
  user1_id: z.number().int().min(0).optional(),
  user2_id: z.number().int().min(0).optional(),
});
