/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { postChatsResponseSchema } from "./postChatsResponseSchema";
import { z } from "zod";

export const postChatsSchema = z.object({
  user1_id: z.number().int().min(0).optional(),
  user2_id: z.number().int().min(0).optional(),
});

/**
 * @description Chats Created success
 */
export const postChats200Schema = z.lazy(() => postChatsResponseSchema);

/**
 * @description Failure
 */
export const postChats400Schema = z.lazy(() => errorResponseSchema);

export const postChatsErrorSchema = z.any();

/**
 * @description Chats Created
 */
export const postChatsMutationRequestSchema = z.lazy(() => postChatsSchema);

export const postChatsMutationResponseSchema = z.lazy(() => postChats200Schema);
