/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { postAuthResponseSchema } from "./postAuthResponseSchema";
import { z } from "zod";

export const postAuthSchema = z.object({
  password: z.string().optional(),
  username: z.string().optional(),
});

/**
 * @description Authentication success
 */
export const postAuth200Schema = z.lazy(() => postAuthResponseSchema);

/**
 * @description Failure
 */
export const postAuth400Schema = z.lazy(() => errorResponseSchema);

export const postAuthErrorSchema = z.any();

/**
 * @description Authentication
 */
export const postAuthMutationRequestSchema = z.lazy(() => postAuthSchema);

export const postAuthMutationResponseSchema = z.lazy(() => postAuth200Schema);
