/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { postSignUpResponseSchema } from "./postSignUpResponseSchema";
import { z } from "zod";

export const postAuthSignUpSchema = z.object({
  email: z.string().optional(),
  first_name: z.string().optional(),
  password: z.string().optional(),
  surname: z.string().optional(),
  username: z.string().optional(),
});

/**
 * @description Create account success
 */
export const postAuthSignUp200Schema = z.lazy(() => postSignUpResponseSchema);

/**
 * @description Failure
 */
export const postAuthSignUp400Schema = z.lazy(() => errorResponseSchema);

export const postAuthSignUpErrorSchema = z.any();

/**
 * @description Authentication Sign Up
 */
export const postAuthSignUpMutationRequestSchema = z.lazy(
  () => postAuthSignUpSchema,
);

export const postAuthSignUpMutationResponseSchema = z.lazy(
  () => postAuthSignUp200Schema,
);
