/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { postEvaluationKeyBodySchema } from "./postEvaluationKeyBodySchema";
import { postEvaluationKeyPartialSchema } from "./postEvaluationKeyPartialSchema";
import { z } from "zod";

/**
 * @description Send eval key success
 */
export const postEvaluationKey200Schema = z.any();

/**
 * @description Accepted
 */
export const postEvaluationKey202Schema = z.lazy(
  () => postEvaluationKeyPartialSchema,
);

/**
 * @description Failure
 */
export const postEvaluationKey400Schema = z.lazy(() => errorResponseSchema);

export const postEvaluationKeyErrorSchema = z.any();

/**
 * @description Send evaluation key to model service body
 */
export const postEvaluationKeyMutationRequestSchema = z.lazy(
  () => postEvaluationKeyBodySchema,
);

export const postEvaluationKeyMutationResponseSchema = z.union([
  z.lazy(() => postEvaluationKey200Schema),
  z.lazy(() => postEvaluationKey202Schema),
]);
