/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorResponseSchema } from "./errorResponseSchema";
import { postEvaluationKeyBodySchema } from "./postEvaluationKeyBodySchema";
import { z } from "zod";

export const postEvaluationKeySchema = z.object({
  file: z.string().optional(),
  id: z.string().optional(),
  user_id: z.number().int().optional(),
});

/**
 * @description Send eval key success
 */
export const postEvaluationKey200Schema = z.lazy(() => postEvaluationKeySchema);

/**
 * @description Failure
 */
export const postEvaluationKey400Schema = z.lazy(() => errorResponseSchema);

export const postEvaluationKeyErrorSchema = z.any();

/**
 * @description Send evaluation key to model service body
 */
export const postEvaluationKeyMutationRequestSchema = z.lazy(
  () => postEvaluationKeyBodySchema,
);

export const postEvaluationKeyMutationResponseSchema = z.lazy(
  () => postEvaluationKey200Schema,
);
