/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const postSignUpResponseSchema = z.object({
  email: z.string().optional(),
  first_name: z.string().optional(),
  id: z.number().int().optional(),
  surname: z.string().optional(),
  username: z.string().optional(),
});
