/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const decryptedMessageSchema = z.object({
  chat_id: z.number().int(),
  sender_id: z.number().int(),
  sender_name: z.string(),
  receiver_id: z.number().int(),
  content: z.string(),
  image: z.string().optional(),
  iv: z.string().optional(),
  type: z.string(),
  is_typing: z.boolean().optional(),
  timestamp: z.string().datetime(),
  classification_result: z.boolean(),
});
