/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const errorSchema = z.object({
  code: z.number().int().describe("Error code").optional(),
  status: z.string().describe("Error name").optional(),
  message: z.string().describe("Error message").optional(),
  errors: z.object({}).catchall(z.any()).describe("Errors").optional(),
});
