/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

export const getClientUserIdPathParamsSchema = z.object({
  user_id: z.coerce.number().int().min(0),
});

/**
 * @description OK
 */
export const getClientUserId200Schema = z.any();

/**
 * @description Bad Request
 */
export const getClientUserId400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Default error response
 */
export const getClientUserIdErrorSchema = z.lazy(() => errorSchema);

export const getClientUserIdQueryResponseSchema = z.lazy(
  () => getClientUserId200Schema,
);
