/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

export const getClientChatIdPathParamsSchema = z.object({
  chat_id: z.coerce.number().int().min(0),
});

/**
 * @description OK
 */
export const getClientChatId200Schema = z.any();

/**
 * @description Bad Request
 */
export const getClientChatId400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Default error response
 */
export const getClientChatIdErrorSchema = z.lazy(() => errorSchema);

export const getClientChatIdQueryResponseSchema = z.lazy(
  () => getClientChatId200Schema,
);
