/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { getMessages200Schema } from "./getMessages200Schema";
import { z } from "zod";

export const getMessagesChatIdPathParamsSchema = z.object({
  chat_id: z.coerce.number().int().min(0),
});

export const getMessagesChatIdQueryParamsSchema = z
  .object({
    skip: z.coerce.number().int().optional(),
    order_by: z.string().optional(),
    sort_by: z.string().optional(),
  })
  .optional();

/**
 * @description OK
 */
export const getMessagesChatId200Schema = z.lazy(() => getMessages200Schema);

/**
 * @description Bad Request
 */
export const getMessagesChatId400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const getMessagesChatId422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const getMessagesChatIdErrorSchema = z.lazy(() => errorSchema);

export const getMessagesChatIdQueryResponseSchema = z.lazy(
  () => getMessagesChatId200Schema,
);
