/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { encryptedMessageSchema } from "./encryptedMessageSchema";
import { metaSchema } from "./metaSchema";
import { z } from "zod";

export const getMessages200Schema = z.object({
  array: z.array(z.lazy(() => encryptedMessageSchema)),
  meta: z.lazy(() => metaSchema),
});
