/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

export const getNormalKeysChatIdPathParamsSchema = z.object({
  chat_id: z.coerce.number().int().min(0),
});

/**
 * @description OK
 */
export const getNormalKeysChatId200Schema = z.any();

/**
 * @description Bad Request
 */
export const getNormalKeysChatId400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Default error response
 */
export const getNormalKeysChatIdErrorSchema = z.lazy(() => errorSchema);

export const getNormalKeysChatIdQueryResponseSchema = z.lazy(
  () => getNormalKeysChatId200Schema,
);
