/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const paginationMetadataSchema = z.object({
  total: z.number().int().optional(),
  total_pages: z.number().int().optional(),
  first_page: z.number().int().optional(),
  last_page: z.number().int().optional(),
  page: z.number().int().optional(),
  previous_page: z.number().int().optional(),
  next_page: z.number().int().optional(),
});
