/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { decryptedMessageSchema } from "./decryptedMessageSchema";
import { decryptMessageBodySchema } from "./decryptMessageBodySchema";
import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postDecrypt200Schema = z.lazy(() => decryptedMessageSchema);

/**
 * @description Bad Request
 */
export const postDecrypt400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postDecrypt422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postDecryptErrorSchema = z.lazy(() => errorSchema);

export const postDecryptMutationRequestSchema = z.lazy(
  () => decryptMessageBodySchema,
);

export const postDecryptMutationResponseSchema = z.lazy(
  () => postDecrypt200Schema,
);
