/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { messageBodySchema } from "./messageBodySchema";
import { messageSchema } from "./messageSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postDecrypt200Schema = z.lazy(() => messageSchema);

/**
 * @description Bad Request
 */
export const postDecrypt400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postDecrypt422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postDecryptErrorSchema = z.lazy(() => errorSchema);

export const postDecryptMutationRequestSchema = z.lazy(() => messageBodySchema);

export const postDecryptMutationResponseSchema = z.lazy(
  () => postDecrypt200Schema,
);
