/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { messageBodySchema } from "./messageBodySchema";
import { messageSchema } from "./messageSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postEncrypt200Schema = z.lazy(() => messageSchema);

/**
 * @description Bad Request
 */
export const postEncrypt400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postEncrypt422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postEncryptErrorSchema = z.lazy(() => errorSchema);

export const postEncryptMutationRequestSchema = z.lazy(() => messageBodySchema);

export const postEncryptMutationResponseSchema = z.lazy(
  () => postEncrypt200Schema,
);
