/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { decryptedMessageSchema } from "./decryptedMessageSchema";
import { encryptMessageBodySchema } from "./encryptMessageBodySchema";
import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postMessage200Schema = z.lazy(() => decryptedMessageSchema);

/**
 * @description Bad Request
 */
export const postMessage400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postMessage422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postMessageErrorSchema = z.lazy(() => errorSchema);

export const postMessageMutationRequestSchema = z.lazy(
  () => encryptMessageBodySchema,
);

export const postMessageMutationResponseSchema = z.lazy(
  () => postMessage200Schema,
);
