/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { encryptedMessageSchema } from "./encryptedMessageSchema";
import { encryptMessageBodySchema } from "./encryptMessageBodySchema";
import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postEncrypt200Schema = z.lazy(() => encryptedMessageSchema);

/**
 * @description Bad Request
 */
export const postEncrypt400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postEncrypt422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postEncryptErrorSchema = z.lazy(() => errorSchema);

export const postEncryptMutationRequestSchema = z.lazy(
  () => encryptMessageBodySchema,
);

export const postEncryptMutationResponseSchema = z.lazy(
  () => postEncrypt200Schema,
);
