/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { errorTypeSchema } from "./errorTypeSchema";
import { messageBodySchema } from "./messageBodySchema";
import { messageSchema } from "./messageSchema";
import { z } from "zod";

/**
 * @description OK
 */
export const postMessage200Schema = z.lazy(() => messageSchema);

/**
 * @description Bad Request
 */
export const postMessage400Schema = z.lazy(() => errorTypeSchema);

/**
 * @description Unprocessable Entity
 */
export const postMessage422Schema = z.lazy(() => errorSchema);

/**
 * @description Default error response
 */
export const postMessageErrorSchema = z.lazy(() => errorSchema);

export const postMessageMutationRequestSchema = z.lazy(() => messageBodySchema);

export const postMessageMutationResponseSchema = z.lazy(
  () => postMessage200Schema,
);
