/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema";
import { z } from "zod";

export const UNPROCESSABLEENTITYSchema = z.lazy(() => errorSchema);
