/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type { GetChatsQueryResponse, GetChats400 } from "../types/GetChats";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getChatsQueryKey = () => [{ url: "/chats" }] as const;

export type GetChatsQueryKey = ReturnType<typeof getChatsQueryKey>;

/**
 * @summary Get chat list
 * {@link /chats}
 */
export async function getChats(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetChatsQueryResponse,
    ResponseErrorConfig<GetChats400>,
    unknown
  >({ method: "GET", url: `/chats`, ...requestConfig });
  return res.data;
}

export function getChatsQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getChatsQueryKey();
  return queryOptions<
    GetChatsQueryResponse,
    ResponseErrorConfig<GetChats400>,
    GetChatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getChats(config);
    },
  });
}

/**
 * @summary Get chat list
 * {@link /chats}
 */
export function useGetChats<
  TData = GetChatsQueryResponse,
  TQueryData = GetChatsQueryResponse,
  TQueryKey extends QueryKey = GetChatsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetChatsQueryResponse,
        ResponseErrorConfig<GetChats400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getChatsQueryKey();

  const query = useQuery(
    {
      ...getChatsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetChats400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
