/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetMessagesQueryResponse,
  GetMessagesPathParams,
  GetMessagesQueryParams,
  GetMessages400,
} from "../types/GetMessages";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMessagesSuspenseQueryKey = (
  chatID: GetMessagesPathParams["chatID"],
  params?: GetMessagesQueryParams,
) =>
  [
    { url: "/messages/:chatID", params: { chatID: chatID } },
    ...(params ? [params] : []),
  ] as const;

export type GetMessagesSuspenseQueryKey = ReturnType<
  typeof getMessagesSuspenseQueryKey
>;

/**
 * @summary Get messages for a chat
 * {@link /messages/:chatID}
 */
export async function getMessagesSuspense(
  chatID: GetMessagesPathParams["chatID"],
  params?: GetMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesQueryResponse,
    ResponseErrorConfig<GetMessages400>,
    unknown
  >({
    method: "GET",
    url: `/messages/${chatID}`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getMessagesSuspenseQueryOptions(
  chatID: GetMessagesPathParams["chatID"],
  params?: GetMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMessagesSuspenseQueryKey(chatID, params);
  return queryOptions<
    GetMessagesQueryResponse,
    ResponseErrorConfig<GetMessages400>,
    GetMessagesQueryResponse,
    typeof queryKey
  >({
    enabled: !!chatID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMessagesSuspense(chatID, params, config);
    },
  });
}

/**
 * @summary Get messages for a chat
 * {@link /messages/:chatID}
 */
export function useGetMessagesSuspense<
  TData = GetMessagesQueryResponse,
  TQueryKey extends QueryKey = GetMessagesSuspenseQueryKey,
>(
  chatID: GetMessagesPathParams["chatID"],
  params?: GetMessagesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMessagesQueryResponse,
        ResponseErrorConfig<GetMessages400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getMessagesSuspenseQueryKey(chatID, params);

  const query = useSuspenseQuery(
    {
      ...getMessagesSuspenseQueryOptions(chatID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetMessages400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
