/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetMessagesCountQueryResponse,
  GetMessagesCountPathParams,
  GetMessagesCountQueryParams,
  GetMessagesCount400,
} from "../types/GetMessagesCount";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMessagesCountSuspenseQueryKey = (
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
) =>
  [
    { url: "/messages/:chatID/count", params: { chatID: chatID } },
    ...(params ? [params] : []),
  ] as const;

export type GetMessagesCountSuspenseQueryKey = ReturnType<
  typeof getMessagesCountSuspenseQueryKey
>;

/**
 * @summary Get message count
 * {@link /messages/:chatID/count}
 */
export async function getMessagesCountSuspense(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesCountQueryResponse,
    ResponseErrorConfig<GetMessagesCount400>,
    unknown
  >({
    method: "GET",
    url: `/messages/${chatID}/count`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getMessagesCountSuspenseQueryOptions(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMessagesCountSuspenseQueryKey(chatID, params);
  return queryOptions<
    GetMessagesCountQueryResponse,
    ResponseErrorConfig<GetMessagesCount400>,
    GetMessagesCountQueryResponse,
    typeof queryKey
  >({
    enabled: !!chatID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMessagesCountSuspense(chatID, params, config);
    },
  });
}

/**
 * @summary Get message count
 * {@link /messages/:chatID/count}
 */
export function useGetMessagesCountSuspense<
  TData = GetMessagesCountQueryResponse,
  TQueryKey extends QueryKey = GetMessagesCountSuspenseQueryKey,
>(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMessagesCountQueryResponse,
        ResponseErrorConfig<GetMessagesCount400>,
        TData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getMessagesCountSuspenseQueryKey(chatID, params);

  const query = useSuspenseQuery(
    {
      ...getMessagesCountSuspenseQueryOptions(chatID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetMessagesCount400>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
