/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type { GetUserQueryResponse, GetUser400 } from "../types/GetUser";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUserSuspenseQueryKey = () => [{ url: "/user" }] as const;

export type GetUserSuspenseQueryKey = ReturnType<
  typeof getUserSuspenseQueryKey
>;

/**
 * @summary Get current user info
 * {@link /user}
 */
export async function getUserSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser400>,
    unknown
  >({ method: "GET", url: `/user`, ...requestConfig });
  return res.data;
}

export function getUserSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getUserSuspenseQueryKey();
  return queryOptions<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser400>,
    GetUserQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getUserSuspense(config);
    },
  });
}

/**
 * @summary Get current user info
 * {@link /user}
 */
export function useGetUserSuspense<
  TData = GetUserQueryResponse,
  TQueryKey extends QueryKey = GetUserSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetUserQueryResponse,
        ResponseErrorConfig<GetUser400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getUserSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getUserSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUser400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
