/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetUsersQueryResponse,
  GetUsersQueryParams,
  GetUsers400,
} from "../types/GetUsers";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUsersQueryKey = (params?: GetUsersQueryParams) =>
  [{ url: "/users" }, ...(params ? [params] : [])] as const;

export type GetUsersQueryKey = ReturnType<typeof getUsersQueryKey>;

/**
 * @summary Get users not in chat
 * {@link /users}
 */
export async function getUsers(
  params?: GetUsersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers400>,
    unknown
  >({ method: "GET", url: `/users`, params, ...requestConfig });
  return res.data;
}

export function getUsersQueryOptions(
  params?: GetUsersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getUsersQueryKey(params);
  return queryOptions<
    GetUsersQueryResponse,
    ResponseErrorConfig<GetUsers400>,
    GetUsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getUsers(params, config);
    },
  });
}

/**
 * @summary Get users not in chat
 * {@link /users}
 */
export function useGetUsers<
  TData = GetUsersQueryResponse,
  TQueryData = GetUsersQueryResponse,
  TQueryKey extends QueryKey = GetUsersQueryKey,
>(
  params?: GetUsersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetUsersQueryResponse,
        ResponseErrorConfig<GetUsers400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getUsersQueryKey(params);

  const query = useQuery(
    {
      ...getUsersQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetUsers400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
