/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type { GetChatsQueryResponse, GetChats400 } from "../types/GetChats";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getChatsSuspenseQueryKey = () => [{ url: "/chats" }] as const;

export type GetChatsSuspenseQueryKey = ReturnType<
  typeof getChatsSuspenseQueryKey
>;

/**
 * @summary Get chat list
 * {@link /chats}
 */
export async function getChatsSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetChatsQueryResponse,
    ResponseErrorConfig<GetChats400>,
    unknown
  >({ method: "GET", url: `/chats`, ...requestConfig });
  return res.data;
}

export function getChatsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getChatsSuspenseQueryKey();
  return queryOptions<
    GetChatsQueryResponse,
    ResponseErrorConfig<GetChats400>,
    GetChatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getChatsSuspense(config);
    },
  });
}

/**
 * @summary Get chat list
 * {@link /chats}
 */
export function useGetChatsSuspense<
  TData = GetChatsQueryResponse,
  TQueryKey extends QueryKey = GetChatsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetChatsQueryResponse,
        ResponseErrorConfig<GetChats400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getChatsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getChatsSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetChats400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
