/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetRefreshTokenQueryResponse,
  GetRefreshToken400,
} from "../types/GetRefreshToken";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getRefreshTokenQueryKey = () =>
  [{ url: "/auth/refresh" }] as const;

export type GetRefreshTokenQueryKey = ReturnType<
  typeof getRefreshTokenQueryKey
>;

/**
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export async function getRefreshToken(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetRefreshTokenQueryResponse,
    ResponseErrorConfig<GetRefreshToken400>,
    unknown
  >({
    method: "GET",
    url: `/auth/refresh`,
    ...requestConfig,
  });
  return res.data;
}

export function getRefreshTokenQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getRefreshTokenQueryKey();
  return queryOptions<
    GetRefreshTokenQueryResponse,
    ResponseErrorConfig<GetRefreshToken400>,
    GetRefreshTokenQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getRefreshToken(config);
    },
  });
}

/**
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export function useGetRefreshToken<
  TData = GetRefreshTokenQueryResponse,
  TQueryData = GetRefreshTokenQueryResponse,
  TQueryKey extends QueryKey = GetRefreshTokenQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetRefreshTokenQueryResponse,
        ResponseErrorConfig<GetRefreshToken400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getRefreshTokenQueryKey();

  const query = useQuery(
    {
      ...getRefreshTokenQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetRefreshToken400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
