/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetEncryptedMessagesQueryResponse,
  GetEncryptedMessagesPathParams,
  GetEncryptedMessagesQueryParams,
  GetEncryptedMessages400,
} from "../types/GetEncryptedMessages";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getEncryptedMessagesQueryKey = (
  chatID: GetEncryptedMessagesPathParams["chatID"],
  params?: GetEncryptedMessagesQueryParams,
) =>
  [
    { url: "/encrypted-messages/:chatID", params: { chatID: chatID } },
    ...(params ? [params] : []),
  ] as const;

export type GetEncryptedMessagesQueryKey = ReturnType<
  typeof getEncryptedMessagesQueryKey
>;

/**
 * @summary Get messages for a chat
 * {@link /encrypted-messages/:chatID}
 */
export async function getEncryptedMessages(
  chatID: GetEncryptedMessagesPathParams["chatID"],
  params?: GetEncryptedMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetEncryptedMessagesQueryResponse,
    ResponseErrorConfig<GetEncryptedMessages400>,
    unknown
  >({
    method: "GET",
    url: `/encrypted-messages/${chatID}`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getEncryptedMessagesQueryOptions(
  chatID: GetEncryptedMessagesPathParams["chatID"],
  params?: GetEncryptedMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getEncryptedMessagesQueryKey(chatID, params);
  return queryOptions<
    GetEncryptedMessagesQueryResponse,
    ResponseErrorConfig<GetEncryptedMessages400>,
    GetEncryptedMessagesQueryResponse,
    typeof queryKey
  >({
    enabled: !!chatID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getEncryptedMessages(chatID, params, config);
    },
  });
}

/**
 * @summary Get messages for a chat
 * {@link /encrypted-messages/:chatID}
 */
export function useGetEncryptedMessages<
  TData = GetEncryptedMessagesQueryResponse,
  TQueryData = GetEncryptedMessagesQueryResponse,
  TQueryKey extends QueryKey = GetEncryptedMessagesQueryKey,
>(
  chatID: GetEncryptedMessagesPathParams["chatID"],
  params?: GetEncryptedMessagesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEncryptedMessagesQueryResponse,
        ResponseErrorConfig<GetEncryptedMessages400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getEncryptedMessagesQueryKey(chatID, params);

  const query = useQuery(
    {
      ...getEncryptedMessagesQueryOptions(chatID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetEncryptedMessages400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
