/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetMessagesCountQueryResponse,
  GetMessagesCountPathParams,
  GetMessagesCountQueryParams,
  GetMessagesCount400,
} from "../types/GetMessagesCount";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMessagesCountQueryKey = (
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
) =>
  [
    { url: "/messages/:chatID/count", params: { chatID: chatID } },
    ...(params ? [params] : []),
  ] as const;

export type GetMessagesCountQueryKey = ReturnType<
  typeof getMessagesCountQueryKey
>;

/**
 * @summary Get message count
 * {@link /messages/:chatID/count}
 */
export async function getMessagesCount(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesCountQueryResponse,
    ResponseErrorConfig<GetMessagesCount400>,
    unknown
  >({
    method: "GET",
    url: `/messages/${chatID}/count`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getMessagesCountQueryOptions(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMessagesCountQueryKey(chatID, params);
  return queryOptions<
    GetMessagesCountQueryResponse,
    ResponseErrorConfig<GetMessagesCount400>,
    GetMessagesCountQueryResponse,
    typeof queryKey
  >({
    enabled: !!chatID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMessagesCount(chatID, params, config);
    },
  });
}

/**
 * @summary Get message count
 * {@link /messages/:chatID/count}
 */
export function useGetMessagesCount<
  TData = GetMessagesCountQueryResponse,
  TQueryData = GetMessagesCountQueryResponse,
  TQueryKey extends QueryKey = GetMessagesCountQueryKey,
>(
  chatID: GetMessagesCountPathParams["chatID"],
  params?: GetMessagesCountQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMessagesCountQueryResponse,
        ResponseErrorConfig<GetMessagesCount400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getMessagesCountQueryKey(chatID, params);

  const query = useQuery(
    {
      ...getMessagesCountQueryOptions(chatID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetMessagesCount400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
