/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  GetRefreshTokenQueryResponse,
  GetRefreshToken400,
} from "../types/GetRefreshToken";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getRefreshTokenSuspenseQueryKey = () =>
  [{ url: "/auth/refresh" }] as const;

export type GetRefreshTokenSuspenseQueryKey = ReturnType<
  typeof getRefreshTokenSuspenseQueryKey
>;

/**
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export async function getRefreshTokenSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetRefreshTokenQueryResponse,
    ResponseErrorConfig<GetRefreshToken400>,
    unknown
  >({
    method: "GET",
    url: `/auth/refresh`,
    ...requestConfig,
  });
  return res.data;
}

export function getRefreshTokenSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getRefreshTokenSuspenseQueryKey();
  return queryOptions<
    GetRefreshTokenQueryResponse,
    ResponseErrorConfig<GetRefreshToken400>,
    GetRefreshTokenQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getRefreshTokenSuspense(config);
    },
  });
}

/**
 * @summary Refresh access token
 * {@link /auth/refresh}
 */
export function useGetRefreshTokenSuspense<
  TData = GetRefreshTokenQueryResponse,
  TQueryKey extends QueryKey = GetRefreshTokenSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetRefreshTokenQueryResponse,
        ResponseErrorConfig<GetRefreshToken400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getRefreshTokenSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getRefreshTokenSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetRefreshToken400>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
