/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  PostEvaluationKeyMutationRequest,
  PostEvaluationKeyMutationResponse,
  PostEvaluationKey400,
} from "../types/PostEvaluationKey";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postEvaluationKeyMutationKey = () =>
  [{ url: "/evaluation-key" }] as const;

export type PostEvaluationKeyMutationKey = ReturnType<
  typeof postEvaluationKeyMutationKey
>;

/**
 * @summary Sende evaluation key to model service
 * {@link /evaluation-key}
 */
export async function postEvaluationKey(
  data?: PostEvaluationKeyMutationRequest,
  config: Partial<RequestConfig<PostEvaluationKeyMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    PostEvaluationKeyMutationResponse,
    ResponseErrorConfig<PostEvaluationKey400>,
    PostEvaluationKeyMutationRequest
  >({
    method: "POST",
    url: `/evaluation-key`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Sende evaluation key to model service
 * {@link /evaluation-key}
 */
export function usePostEvaluationKey<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostEvaluationKeyMutationResponse,
      ResponseErrorConfig<PostEvaluationKey400>,
      { data?: PostEvaluationKeyMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostEvaluationKeyMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postEvaluationKeyMutationKey();

  return useMutation<
    PostEvaluationKeyMutationResponse,
    ResponseErrorConfig<PostEvaluationKey400>,
    { data?: PostEvaluationKeyMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postEvaluationKey(data, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
