/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  PostChatsMutationRequest,
  PostChatsMutationResponse,
  PostChats400,
} from "../types/PostChats";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postChatsMutationKey = () => [{ url: "/chats" }] as const;

export type PostChatsMutationKey = ReturnType<typeof postChatsMutationKey>;

/**
 * @summary Post chat
 * {@link /chats}
 */
export async function postChats(
  data?: PostChatsMutationRequest,
  config: Partial<RequestConfig<PostChatsMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    PostChatsMutationResponse,
    ResponseErrorConfig<PostChats400>,
    PostChatsMutationRequest
  >({
    method: "POST",
    url: `/chats`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Post chat
 * {@link /chats}
 */
export function usePostChats<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostChatsMutationResponse,
      ResponseErrorConfig<PostChats400>,
      { data?: PostChatsMutationRequest },
      TContext
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig<PostChatsMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postChatsMutationKey();

  return useMutation<
    PostChatsMutationResponse,
    ResponseErrorConfig<PostChats400>,
    { data?: PostChatsMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postChats(data, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
