/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client";
import type {
  PostAuthSignUpMutationRequest,
  PostAuthSignUpMutationResponse,
  PostAuthSignUp400,
} from "../types/PostAuthSignUp";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const postAuthSignUpMutationKey = () =>
  [{ url: "/auth/signup" }] as const;

export type PostAuthSignUpMutationKey = ReturnType<
  typeof postAuthSignUpMutationKey
>;

/**
 * @summary Create new account
 * {@link /auth/signup}
 */
export async function postAuthSignUp(
  data?: PostAuthSignUpMutationRequest,
  config: Partial<RequestConfig<PostAuthSignUpMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    PostAuthSignUpMutationResponse,
    ResponseErrorConfig<PostAuthSignUp400>,
    PostAuthSignUpMutationRequest
  >({
    method: "POST",
    url: `/auth/signup`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Create new account
 * {@link /auth/signup}
 */
export function usePostAuthSignUp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthSignUpMutationResponse,
      ResponseErrorConfig<PostAuthSignUp400>,
      { data?: PostAuthSignUpMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthSignUpMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthSignUpMutationKey();

  return useMutation<
    PostAuthSignUpMutationResponse,
    ResponseErrorConfig<PostAuthSignUp400>,
    { data?: PostAuthSignUpMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postAuthSignUp(data, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
