/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ErrorResponse = {
  /**
   * @type integer | undefined
   */
  code?: number;
  /**
   * @type object | undefined
   */
  error?: {
    /**
     * @type string | undefined
     */
    message?: string;
    /**
     * @type string | undefined
     */
    section?: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type integer | undefined
   */
  type?: number;
};
