/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetChats = {
  /**
   * @type array | undefined
   */
  chats?: {
    /**
     * @type string | undefined, date-time
     */
    created_at?: string;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    id?: number;
    /**
     * @type string | undefined, date-time
     */
    last_message_time?: string;
    /**
     * @type boolean | undefined
     */
    seen?: boolean;
    /**
     * @type string | undefined, date-time
     */
    updated_at?: string;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    user1_id?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    user2_id?: number;
  }[];
  /**
   * @type array | undefined
   */
  users?: {
    /**
     * @type string | undefined, date-time
     */
    created_at?: string;
    /**
     * @type string | undefined
     */
    email?: string;
    /**
     * @type string | undefined
     */
    first_name?: string;
    /**
     * @type integer | undefined, int64
     */
    id?: number;
    /**
     * @type string | undefined
     */
    surname?: string;
    /**
     * @type string | undefined
     */
    username?: string;
  }[];
};

/**
 * @description Chats retrieved
 */
export type GetChats200 = GetChats;

/**
 * @description Failure
 */
export type GetChats400 = ErrorResponse;

export type GetChatsError = any;

export type GetChatsQueryResponse = GetChats200;

export type GetChatsQuery = {
  Response: GetChats200;
  Errors: GetChats400;
};
