/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetEncryptedMessages = {
  /**
   * @type array | undefined
   */
  array?: {
    /**
     * @minLength 0
     * @type integer | undefined
     */
    chat_id?: number;
    /**
     * @type string | undefined
     */
    content?: string;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    id?: number;
    /**
     * @type string | undefined
     */
    image?: string;
    /**
     * @type boolean | undefined
     */
    is_typing?: boolean;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    receiver_id?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    sender_id?: number;
    /**
     * @type string | undefined
     */
    sender_name?: string;
    /**
     * @type string | undefined, date-time
     */
    timestamp?: string;
    /**
     * @type string | undefined
     */
    type?: string;
  }[];
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type integer
     */
    total?: number | null;
  };
};

export type GetEncryptedMessagesPathParams = {
  /**
   * @type integer
   */
  chatID: number;
};

export type GetEncryptedMessagesQueryParams = {
  /**
   * @type integer | undefined
   */
  skip?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @type string | undefined
   */
  order_by?: string;
  /**
   * @type string | undefined
   */
  sort_by?: string;
};

/**
 * @description Encrypted Messages retrieved
 */
export type GetEncryptedMessages200 = GetEncryptedMessages;

/**
 * @description Failure
 */
export type GetEncryptedMessages400 = ErrorResponse;

export type GetEncryptedMessagesError = any;

export type GetEncryptedMessagesQueryResponse = GetEncryptedMessages200;

export type GetEncryptedMessagesQuery = {
  Response: GetEncryptedMessages200;
  PathParams: GetEncryptedMessagesPathParams;
  QueryParams: GetEncryptedMessagesQueryParams;
  Errors: GetEncryptedMessages400;
};
