/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetEvaluationKey = {
  /**
   * @type integer | undefined, int32
   */
  chat_id?: number;
  /**
   * @type string | undefined
   */
  file?: string;
  /**
   * @type string | undefined
   */
  id?: string;
};

/**
 * @description Get eval key success
 */
export type GetEvaluationKey200 = GetEvaluationKey;

/**
 * @description Failure
 */
export type GetEvaluationKey400 = ErrorResponse;

export type GetEvaluationKeyError = any;

export type GetEvaluationKeyQueryResponse = GetEvaluationKey200;

export type GetEvaluationKeyQuery = {
  Response: GetEvaluationKey200;
  Errors: GetEvaluationKey400;
};
