/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetMessagesCountPathParams = {
  /**
   * @type integer
   */
  chatID: number;
};

export type GetMessagesCountQueryParams = {
  /**
   * @type integer | undefined
   */
  skip?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
};

/**
 * @description Count retrieved
 */
export type GetMessagesCount200 = number;

/**
 * @description Failure
 */
export type GetMessagesCount400 = ErrorResponse;

export type GetMessagesCountError = any;

export type GetMessagesCountQueryResponse = GetMessagesCount200;

export type GetMessagesCountQuery = {
  Response: GetMessagesCount200;
  PathParams: GetMessagesCountPathParams;
  QueryParams: GetMessagesCountQueryParams;
  Errors: GetMessagesCount400;
};
