/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetMessages = {
  /**
   * @type array | undefined
   */
  array?: {
    /**
     * @minLength 0
     * @type integer | undefined
     */
    chat_id?: number;
    /**
     * @type string | undefined
     */
    classification_result?: string;
    /**
     * @type string | undefined
     */
    content?: string;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    id?: number;
    /**
     * @type string | undefined
     */
    image?: string;
    /**
     * @type boolean | undefined
     */
    is_typing?: boolean;
    /**
     * @type string | undefined
     */
    iv?: string;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    receiver_id?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    sender_id?: number;
    /**
     * @type string | undefined
     */
    sender_name?: string;
    /**
     * @type string | undefined, date-time
     */
    timestamp?: string;
    /**
     * @type string | undefined
     */
    type?: string;
  }[];
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type integer
     */
    total?: number | null;
  };
};

export type GetMessagesPathParams = {
  /**
   * @type integer
   */
  chatID: number;
};

export type GetMessagesQueryParams = {
  /**
   * @type integer | undefined
   */
  skip?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @type string | undefined
   */
  order_by?: string;
  /**
   * @type string | undefined
   */
  sort_by?: string;
};

/**
 * @description Messages retrieved
 */
export type GetMessages200 = GetMessages;

/**
 * @description Failure
 */
export type GetMessages400 = ErrorResponse;

export type GetMessagesError = any;

export type GetMessagesQueryResponse = GetMessages200;

export type GetMessagesQuery = {
  Response: GetMessages200;
  PathParams: GetMessagesPathParams;
  QueryParams: GetMessagesQueryParams;
  Errors: GetMessages400;
};
