/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { GetRefreshAuthResponse } from "./GetRefreshAuthResponse";

/**
 * @description Refresh Authentication success
 */
export type GetRefreshToken200 = GetRefreshAuthResponse;

/**
 * @description Failure
 */
export type GetRefreshToken400 = ErrorResponse;

export type GetRefreshTokenError = any;

export type GetRefreshTokenQueryResponse = GetRefreshToken200;

export type GetRefreshTokenQuery = {
  Response: GetRefreshToken200;
  Errors: GetRefreshToken400;
};
