/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetUser = {
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  first_name?: string;
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type string | undefined
   */
  surname?: string;
  /**
   * @type string | undefined
   */
  username?: string;
};

/**
 * @description User retrieved
 */
export type GetUser200 = GetUser;

/**
 * @description Failure
 */
export type GetUser400 = ErrorResponse;

export type GetUserError = any;

export type GetUserQueryResponse = GetUser200;

export type GetUserQuery = {
  Response: GetUser200;
  Errors: GetUser400;
};
