/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";

export type GetUsers = {
  /**
   * @type array | undefined
   */
  array?: {
    /**
     * @type string | undefined
     */
    email?: string;
    /**
     * @type string | undefined
     */
    first_name?: string;
    /**
     * @type integer | undefined, int64
     */
    id?: number;
    /**
     * @type string | undefined
     */
    surname?: string;
    /**
     * @type string | undefined
     */
    username?: string;
  }[];
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type integer
     */
    total?: number | null;
  };
};

export type GetUsersQueryParams = {
  /**
   * @type integer | undefined
   */
  skip?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @type string | undefined
   */
  order_by?: string;
  /**
   * @type string | undefined
   */
  sort_by?: string;
};

/**
 * @description Users retrieved
 */
export type GetUsers200 = GetUsers;

/**
 * @description Failure
 */
export type GetUsers400 = ErrorResponse;

export type GetUsersError = any;

export type GetUsersQueryResponse = GetUsers200;

export type GetUsersQuery = {
  Response: GetUsers200;
  QueryParams: GetUsersQueryParams;
  Errors: GetUsers400;
};
