/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostSignUpResponse = {
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  first_name?: string;
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type string | undefined
   */
  surname?: string;
  /**
   * @type string | undefined
   */
  username?: string;
};
