/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { PostAuthResponse } from "./PostAuthResponse";

export type PostAuth = {
  /**
   * @type string | undefined
   */
  password?: string;
  /**
   * @type string | undefined
   */
  username?: string;
};

/**
 * @description Authentication success
 */
export type PostAuth200 = PostAuthResponse;

/**
 * @description Failure
 */
export type PostAuth400 = ErrorResponse;

export type PostAuthError = any;

/**
 * @description Authentication
 */
export type PostAuthMutationRequest = PostAuth;

export type PostAuthMutationResponse = PostAuth200;

export type PostAuthMutation = {
  Response: PostAuth200;
  Request: PostAuthMutationRequest;
  Errors: PostAuth400;
};
