/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { PostEvaluationKeyBody } from "./PostEvaluationKeyBody";
import type { PostEvaluationKeyPartial } from "./PostEvaluationKeyPartial";

/**
 * @description Send eval key success
 */
export type PostEvaluationKey200 = any;

/**
 * @description Accepted
 */
export type PostEvaluationKey202 = PostEvaluationKeyPartial;

/**
 * @description Failure
 */
export type PostEvaluationKey400 = ErrorResponse;

export type PostEvaluationKeyError = any;

/**
 * @description Send evaluation key to model service body
 */
export type PostEvaluationKeyMutationRequest = PostEvaluationKeyBody;

export type PostEvaluationKeyMutationResponse =
  | PostEvaluationKey200
  | PostEvaluationKey202;

export type PostEvaluationKeyMutation = {
  Response: PostEvaluationKey200 | PostEvaluationKey202;
  Request: PostEvaluationKeyMutationRequest;
  Errors: PostEvaluationKey400;
};
