/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostEvaluationKeyBody = {
  /**
   * @minLength 0
   * @type integer | undefined
   */
  chat_id?: number;
  /**
   * @type string | undefined
   */
  file?: string;
};
