/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostChatsResponse = {
  /**
   * @type string | undefined, date-time
   */
  created_at?: string;
  /**
   * @minLength 0
   * @type integer | undefined
   */
  id?: number;
  /**
   * @type string | undefined, date-time
   */
  last_message_time?: string;
  /**
   * @type boolean | undefined
   */
  seen?: boolean;
  /**
   * @type string | undefined, date-time
   */
  updated_at?: string;
  /**
   * @minLength 0
   * @type integer | undefined
   */
  user1_id?: number;
  /**
   * @minLength 0
   * @type integer | undefined
   */
  user2_id?: number;
};
