/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { PostEvaluationKeyBody } from "./PostEvaluationKeyBody";

export type PostEvaluationKey = {
  /**
   * @type integer | undefined, int32
   */
  chat_id?: number;
  /**
   * @type string | undefined
   */
  file?: string;
  /**
   * @type string | undefined
   */
  id?: string;
};

/**
 * @description Send eval key success
 */
export type PostEvaluationKey200 = PostEvaluationKey;

/**
 * @description Failure
 */
export type PostEvaluationKey400 = ErrorResponse;

export type PostEvaluationKeyError = any;

/**
 * @description Send evaluation key to model service body
 */
export type PostEvaluationKeyMutationRequest = PostEvaluationKeyBody;

export type PostEvaluationKeyMutationResponse = PostEvaluationKey200;

export type PostEvaluationKeyMutation = {
  Response: PostEvaluationKey200;
  Request: PostEvaluationKeyMutationRequest;
  Errors: PostEvaluationKey400;
};
