/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { PostChatsResponse } from "./PostChatsResponse";

export type PostChats = {
  /**
   * @minLength 0
   * @type integer | undefined
   */
  user1_id?: number;
  /**
   * @minLength 0
   * @type integer | undefined
   */
  user2_id?: number;
};

/**
 * @description Chats Created success
 */
export type PostChats200 = PostChatsResponse;

/**
 * @description Failure
 */
export type PostChats400 = ErrorResponse;

export type PostChatsError = any;

/**
 * @description Chats Created
 */
export type PostChatsMutationRequest = PostChats;

export type PostChatsMutationResponse = PostChats200;

export type PostChatsMutation = {
  Response: PostChats200;
  Request: PostChatsMutationRequest;
  Errors: PostChats400;
};
