/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostAuthResponse = {
  /**
   * @type string | undefined
   */
  access_token?: string;
  /**
   * @type string | undefined, date-time
   */
  exp?: string;
  /**
   * @type string | undefined
   */
  refresh_token?: string;
  /**
   * @type object | undefined
   */
  user?: {
    /**
     * @type string | undefined, date-time
     */
    created_at?: string;
    /**
     * @type string | undefined
     */
    email?: string;
    /**
     * @type string | undefined
     */
    first_name?: string;
    /**
     * @type integer | undefined, int64
     */
    id?: number;
    /**
     * @type string | undefined
     */
    surname?: string;
    /**
     * @type string | undefined
     */
    username?: string;
  };
};
