/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from "./ErrorResponse";
import type { PostSignUpResponse } from "./PostSignUpResponse";

export type PostAuthSignUp = {
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  first_name?: string;
  /**
   * @type string | undefined
   */
  password?: string;
  /**
   * @type string | undefined
   */
  surname?: string;
  /**
   * @type string | undefined
   */
  username?: string;
};

/**
 * @description Create account success
 */
export type PostAuthSignUp200 = PostSignUpResponse;

/**
 * @description Failure
 */
export type PostAuthSignUp400 = ErrorResponse;

export type PostAuthSignUpError = any;

/**
 * @description Authentication Sign Up
 */
export type PostAuthSignUpMutationRequest = PostAuthSignUp;

export type PostAuthSignUpMutationResponse = PostAuthSignUp200;

export type PostAuthSignUpMutation = {
  Response: PostAuthSignUp200;
  Request: PostAuthSignUpMutationRequest;
  Errors: PostAuthSignUp400;
};
