# coding: utf-8

"""
    Key Manager API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.kms_api import KmsApi


class TestKmsApi(unittest.TestCase):
    """KmsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KmsApi()

    def tearDown(self) -> None:
        pass

    def test_client_get(self) -> None:
        """Test case for client_get

        """
        pass

    def test_model_get(self) -> None:
        """Test case for model_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
