/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client2";
import type {
  GetMessagesChatIdQueryResponse,
  GetMessagesChatIdPathParams,
  GetMessagesChatIdQueryParams,
  GetMessagesChatId400,
  GetMessagesChatId422,
} from "../types/GetMessagesChatId";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client2";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMessagesChatIdSuspenseQueryKey = (
  chat_id: GetMessagesChatIdPathParams["chat_id"],
  params?: GetMessagesChatIdQueryParams,
) =>
  [
    { url: "/messages/:chat_id", params: { chat_id: chat_id } },
    ...(params ? [params] : []),
  ] as const;

export type GetMessagesChatIdSuspenseQueryKey = ReturnType<
  typeof getMessagesChatIdSuspenseQueryKey
>;

/**
 * @description Get messages by chat ID with optional sorting and pagination.
 * {@link /messages/:chat_id}
 */
export async function getMessagesChatIdSuspense(
  chat_id: GetMessagesChatIdPathParams["chat_id"],
  params?: GetMessagesChatIdQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesChatIdQueryResponse,
    ResponseErrorConfig<GetMessagesChatId400 | GetMessagesChatId422>,
    unknown
  >({
    method: "GET",
    url: `/messages/${chat_id}`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getMessagesChatIdSuspenseQueryOptions(
  chat_id: GetMessagesChatIdPathParams["chat_id"],
  params?: GetMessagesChatIdQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMessagesChatIdSuspenseQueryKey(chat_id, params);
  return queryOptions<
    GetMessagesChatIdQueryResponse,
    ResponseErrorConfig<GetMessagesChatId400 | GetMessagesChatId422>,
    GetMessagesChatIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!chat_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMessagesChatIdSuspense(chat_id, params, config);
    },
  });
}

/**
 * @description Get messages by chat ID with optional sorting and pagination.
 * {@link /messages/:chat_id}
 */
export function useGetMessagesChatIdSuspense<
  TData = GetMessagesChatIdQueryResponse,
  TQueryKey extends QueryKey = GetMessagesChatIdSuspenseQueryKey,
>(
  chat_id: GetMessagesChatIdPathParams["chat_id"],
  params?: GetMessagesChatIdQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMessagesChatIdQueryResponse,
        ResponseErrorConfig<GetMessagesChatId400 | GetMessagesChatId422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ??
    getMessagesChatIdSuspenseQueryKey(chat_id, params);

  const query = useSuspenseQuery(
    {
      ...getMessagesChatIdSuspenseQueryOptions(chat_id, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetMessagesChatId400 | GetMessagesChatId422>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
