/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client2";
import type {
  GetNormalKeysChatIdQueryResponse,
  GetNormalKeysChatIdPathParams,
  GetNormalKeysChatId400,
} from "../types/GetNormalKeysChatId";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client2";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getNormalKeysChatIdQueryKey = (
  chat_id: GetNormalKeysChatIdPathParams["chat_id"],
) => [{ url: "/normal_keys/:chat_id", params: { chat_id: chat_id } }] as const;

export type GetNormalKeysChatIdQueryKey = ReturnType<
  typeof getNormalKeysChatIdQueryKey
>;

/**
 * @description Encrypt image using FHE.
 * {@link /normal_keys/:chat_id}
 */
export async function getNormalKeysChatId(
  chat_id: GetNormalKeysChatIdPathParams["chat_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetNormalKeysChatIdQueryResponse,
    ResponseErrorConfig<GetNormalKeysChatId400>,
    unknown
  >({
    method: "GET",
    url: `/normal_keys/${chat_id}`,
    ...requestConfig,
  });
  return res.data;
}

export function getNormalKeysChatIdQueryOptions(
  chat_id: GetNormalKeysChatIdPathParams["chat_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getNormalKeysChatIdQueryKey(chat_id);
  return queryOptions<
    GetNormalKeysChatIdQueryResponse,
    ResponseErrorConfig<GetNormalKeysChatId400>,
    GetNormalKeysChatIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!chat_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getNormalKeysChatId(chat_id, config);
    },
  });
}

/**
 * @description Encrypt image using FHE.
 * {@link /normal_keys/:chat_id}
 */
export function useGetNormalKeysChatId<
  TData = GetNormalKeysChatIdQueryResponse,
  TQueryData = GetNormalKeysChatIdQueryResponse,
  TQueryKey extends QueryKey = GetNormalKeysChatIdQueryKey,
>(
  chat_id: GetNormalKeysChatIdPathParams["chat_id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetNormalKeysChatIdQueryResponse,
        ResponseErrorConfig<GetNormalKeysChatId400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getNormalKeysChatIdQueryKey(chat_id);

  const query = useQuery(
    {
      ...getNormalKeysChatIdQueryOptions(chat_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetNormalKeysChatId400>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
