/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client2";
import type {
  GetClientChatIdQueryResponse,
  GetClientChatIdPathParams,
  GetClientChatId400,
} from "../types/GetClientChatId";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client2";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getClientChatIdSuspenseQueryKey = (
  chat_id: GetClientChatIdPathParams["chat_id"],
) => [{ url: "/client/:chat_id", params: { chat_id: chat_id } }] as const;

export type GetClientChatIdSuspenseQueryKey = ReturnType<
  typeof getClientChatIdSuspenseQueryKey
>;

/**
 * @description Generate client configs for FHE.
 * {@link /client/:chat_id}
 */
export async function getClientChatIdSuspense(
  chat_id: GetClientChatIdPathParams["chat_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetClientChatIdQueryResponse,
    ResponseErrorConfig<GetClientChatId400>,
    unknown
  >({
    method: "GET",
    url: `/client/${chat_id}`,
    ...requestConfig,
  });
  return res.data;
}

export function getClientChatIdSuspenseQueryOptions(
  chat_id: GetClientChatIdPathParams["chat_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getClientChatIdSuspenseQueryKey(chat_id);
  return queryOptions<
    GetClientChatIdQueryResponse,
    ResponseErrorConfig<GetClientChatId400>,
    GetClientChatIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!chat_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getClientChatIdSuspense(chat_id, config);
    },
  });
}

/**
 * @description Generate client configs for FHE.
 * {@link /client/:chat_id}
 */
export function useGetClientChatIdSuspense<
  TData = GetClientChatIdQueryResponse,
  TQueryKey extends QueryKey = GetClientChatIdSuspenseQueryKey,
>(
  chat_id: GetClientChatIdPathParams["chat_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetClientChatIdQueryResponse,
        ResponseErrorConfig<GetClientChatId400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getClientChatIdSuspenseQueryKey(chat_id);

  const query = useSuspenseQuery(
    {
      ...getClientChatIdSuspenseQueryOptions(chat_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetClientChatId400>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
