/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/authorized-client2";
import type {
  GetClientUserIdQueryResponse,
  GetClientUserIdPathParams,
  GetClientUserId400,
} from "../types/GetClientUserId";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/authorized-client2";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getClientUserIdSuspenseQueryKey = (
  user_id: GetClientUserIdPathParams["user_id"],
) => [{ url: "/client/:user_id", params: { user_id: user_id } }] as const;

export type GetClientUserIdSuspenseQueryKey = ReturnType<
  typeof getClientUserIdSuspenseQueryKey
>;

/**
 * @description Generate client configs for FHE.
 * {@link /client/:user_id}
 */
export async function getClientUserIdSuspense(
  user_id: GetClientUserIdPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetClientUserIdQueryResponse,
    ResponseErrorConfig<GetClientUserId400>,
    unknown
  >({
    method: "GET",
    url: `/client/${user_id}`,
    ...requestConfig,
  });
  return res.data;
}

export function getClientUserIdSuspenseQueryOptions(
  user_id: GetClientUserIdPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getClientUserIdSuspenseQueryKey(user_id);
  return queryOptions<
    GetClientUserIdQueryResponse,
    ResponseErrorConfig<GetClientUserId400>,
    GetClientUserIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!user_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getClientUserIdSuspense(user_id, config);
    },
  });
}

/**
 * @description Generate client configs for FHE.
 * {@link /client/:user_id}
 */
export function useGetClientUserIdSuspense<
  TData = GetClientUserIdQueryResponse,
  TQueryKey extends QueryKey = GetClientUserIdSuspenseQueryKey,
>(
  user_id: GetClientUserIdPathParams["user_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetClientUserIdQueryResponse,
        ResponseErrorConfig<GetClientUserId400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getClientUserIdSuspenseQueryKey(user_id);

  const query = useSuspenseQuery(
    {
      ...getClientUserIdSuspenseQueryOptions(user_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetClientUserId400>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
