/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Error = {
  /**
   * @description Error code
   * @type integer | undefined
   */
  code?: number;
  /**
   * @description Error name
   * @type string | undefined
   */
  status?: string;
  /**
   * @description Error message
   * @type string | undefined
   */
  message?: string;
  /**
   * @description Errors
   * @type object | undefined
   */
  errors?: {
    [key: string]: any;
  };
};
