/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ErrorType = {
  /**
   * @type string
   */
  section: string;
  /**
   * @type string
   */
  message: string;
};
