/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";

export type GetClientUserIdPathParams = {
  /**
   * @minLength 0
   * @type integer
   */
  user_id: number;
};

/**
 * @description OK
 */
export type GetClientUserId200 = any;

/**
 * @description Bad Request
 */
export type GetClientUserId400 = ErrorType;

/**
 * @description Default error response
 */
export type GetClientUserIdError = Error;

export type GetClientUserIdQueryResponse = GetClientUserId200;

export type GetClientUserIdQuery = {
  Response: GetClientUserId200;
  PathParams: GetClientUserIdPathParams;
  Errors: GetClientUserId400;
};
