/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";

export type GetClientChatIdPathParams = {
  /**
   * @minLength 0
   * @type integer
   */
  chat_id: number;
};

/**
 * @description OK
 */
export type GetClientChatId200 = any;

/**
 * @description Bad Request
 */
export type GetClientChatId400 = ErrorType;

/**
 * @description Default error response
 */
export type GetClientChatIdError = Error;

export type GetClientChatIdQueryResponse = GetClientChatId200;

export type GetClientChatIdQuery = {
  Response: GetClientChatId200;
  PathParams: GetClientChatIdPathParams;
  Errors: GetClientChatId400;
};
