/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";
import type { GetMessages200 } from "./GetMessages200";

export type GetMessagesChatIdPathParams = {
  /**
   * @minLength 0
   * @type integer
   */
  chat_id: number;
};

export type GetMessagesChatIdQueryParams = {
  /**
   * @type integer | undefined
   */
  skip?: number;
  /**
   * @type string | undefined
   */
  order_by?: string;
  /**
   * @type string | undefined
   */
  sort_by?: string;
};

/**
 * @description OK
 */
export type GetMessagesChatId200 = GetMessages200;

/**
 * @description Bad Request
 */
export type GetMessagesChatId400 = ErrorType;

/**
 * @description Unprocessable Entity
 */
export type GetMessagesChatId422 = Error;

/**
 * @description Default error response
 */
export type GetMessagesChatIdError = Error;

export type GetMessagesChatIdQueryResponse = GetMessagesChatId200;

export type GetMessagesChatIdQuery = {
  Response: GetMessagesChatId200;
  PathParams: GetMessagesChatIdPathParams;
  QueryParams: GetMessagesChatIdQueryParams;
  Errors: GetMessagesChatId400 | GetMessagesChatId422;
};
