/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";

export type GetNormalKeysChatIdPathParams = {
  /**
   * @minLength 0
   * @type integer
   */
  chat_id: number;
};

/**
 * @description OK
 */
export type GetNormalKeysChatId200 = any;

/**
 * @description Bad Request
 */
export type GetNormalKeysChatId400 = ErrorType;

/**
 * @description Default error response
 */
export type GetNormalKeysChatIdError = Error;

export type GetNormalKeysChatIdQueryResponse = GetNormalKeysChatId200;

export type GetNormalKeysChatIdQuery = {
  Response: GetNormalKeysChatId200;
  PathParams: GetNormalKeysChatIdPathParams;
  Errors: GetNormalKeysChatId400;
};
