/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Message = {
  /**
   * @type integer
   */
  id: number;
  /**
   * @type integer
   */
  chat_id: number;
  /**
   * @type integer
   */
  sender_id: number;
  /**
   * @type string
   */
  sender_name: string;
  /**
   * @type integer
   */
  receiver_id: number;
  /**
   * @type string
   */
  content: string;
  image?: any;
  /**
   * @type string
   */
  type: string;
  /**
   * @type boolean | undefined
   */
  is_typing?: boolean;
  /**
   * @type string, date-time
   */
  timestamp: string;
};
