/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PaginationMetadata = {
  /**
   * @type integer | undefined
   */
  total?: number;
  /**
   * @type integer | undefined
   */
  total_pages?: number;
  /**
   * @type integer | undefined
   */
  first_page?: number;
  /**
   * @type integer | undefined
   */
  last_page?: number;
  /**
   * @type integer | undefined
   */
  page?: number;
  /**
   * @type integer | undefined
   */
  previous_page?: number;
  /**
   * @type integer | undefined
   */
  next_page?: number;
};
