/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EncryptedMessage } from "./EncryptedMessage";
import type { EncryptMessageBody } from "./EncryptMessageBody";
import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";

/**
 * @description OK
 */
export type PostEncrypt200 = EncryptedMessage;

/**
 * @description Bad Request
 */
export type PostEncrypt400 = ErrorType;

/**
 * @description Unprocessable Entity
 */
export type PostEncrypt422 = Error;

/**
 * @description Default error response
 */
export type PostEncryptError = Error;

export type PostEncryptMutationRequest = EncryptMessageBody;

export type PostEncryptMutationResponse = PostEncrypt200;

export type PostEncryptMutation = {
  Response: PostEncrypt200;
  Request: PostEncryptMutationRequest;
  Errors: PostEncrypt400 | PostEncrypt422;
};
