/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";
import type { Message } from "./Message";
import type { MessageBody } from "./MessageBody";

/**
 * @description OK
 */
export type PostEncrypt200 = Message;

/**
 * @description Bad Request
 */
export type PostEncrypt400 = ErrorType;

/**
 * @description Unprocessable Entity
 */
export type PostEncrypt422 = Error;

/**
 * @description Default error response
 */
export type PostEncryptError = Error;

export type PostEncryptMutationRequest = MessageBody;

export type PostEncryptMutationResponse = PostEncrypt200;

export type PostEncryptMutation = {
  Response: PostEncrypt200;
  Request: PostEncryptMutationRequest;
  Errors: PostEncrypt400 | PostEncrypt422;
};
