/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";
import type { Message } from "./Message";

/**
 * @description OK
 */
export type PostDecrypt200 = Message;

/**
 * @description Bad Request
 */
export type PostDecrypt400 = ErrorType;

/**
 * @description Unprocessable Entity
 */
export type PostDecrypt422 = Error;

/**
 * @description Default error response
 */
export type PostDecryptError = Error;

export type PostDecryptMutationRequest = Message;

export type PostDecryptMutationResponse = PostDecrypt200;

export type PostDecryptMutation = {
  Response: PostDecrypt200;
  Request: PostDecryptMutationRequest;
  Errors: PostDecrypt400 | PostDecrypt422;
};
