/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error";
import type { ErrorType } from "./ErrorType";
import type { Message } from "./Message";
import type { MessageBody } from "./MessageBody";

/**
 * @description OK
 */
export type PostMessage200 = Message;

/**
 * @description Bad Request
 */
export type PostMessage400 = ErrorType;

/**
 * @description Unprocessable Entity
 */
export type PostMessage422 = Error;

/**
 * @description Default error response
 */
export type PostMessageError = Error;

export type PostMessageMutationRequest = MessageBody;

export type PostMessageMutationResponse = PostMessage200;

export type PostMessageMutation = {
  Response: PostMessage200;
  Request: PostMessageMutationRequest;
  Errors: PostMessage400 | PostMessage422;
};
